### ISSUE TITLE
ImportError: No module named 'fpdf'

### ISSUE THREAD

**Issue by DamonDay** [JPYamamoto/Issuu-PDF-Downloader#1]
runfile('D:/python/Issuu-PDF-Downloader-master/framework.py', wdir='D:/python/Issuu-PDF-Downloader-master')
Reloaded modules: core, core.resizer
Traceback (most recent call last):

  File "<ipython-input-5-d05f5b40c2bd>", line 1, in <module>
    runfile('D:/python/Issuu-PDF-Downloader-master/framework.py', wdir='D:/python/Issuu-PDF-Downloader-master')

  File "C:\Users\m1867\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\m1867\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/python/Issuu-PDF-Downloader-master/framework.py", line 3, in <module>
    import core.downloader as program

  File "D:\python\Issuu-PDF-Downloader-master\core\downloader.py", line 4, in <module>
    import core.pdf as pdf

  File "D:\python\Issuu-PDF-Downloader-master\core\pdf.py", line 1, in <module>
    from fpdf import FPDF

**ImportError: No module named 'fpdf'**
anaconda py35, i didn't change any code, just download and run in Spyder
thx a lot

**Comment by jpyamamoto** [comment]
To make it work, you have to install fpdf through pip first.
You can do it by running from your console `pip install fpdf`

**Comment by jpyamamoto** [comment]
Closing due to inactivity
